### ISSUE TITLE
Simplify Multitenancy

### ISSUE THREAD

**Issue by orubel** [orubel/Beapi-API-Framework#112]
Separate out user/validation tables for database into separate database so that it can be shared for multitenancy or multriple instances.

**Comment by orubel** [comment]
Hmmm... from working on this and doing research, this seems to be a big issue due to bugs in GORM and not upgrading to recent versions of spring-boot. I'm going to work on this a little more but this may be something that has to wait until a grails 4.0 upgrade.

**Comment by orubel** [comment]
Yeah this is an ongoing issue for Grails/Gorm. It looks to also be affecting their new project (Micronut) as well and this has been affecting the project since 2016 from the looks of things.

Probably not going to get fixed till Grails 4.0

**Comment by pekatete** [comment]
Oh well, it'll have to wait then I suppose.

**Comment by orubel** [comment]
I do think that part of this does need to be integrated to avoid having all the auth/validation being in the same DB; should be separated at least as a service.
