### ISSUE TITLE
Can it support Grails4.0?

### ISSUE THREAD

**Issue by hanyou** [orubel/Beapi-API-Framework#120]
Can it support Grails4.0?

**Comment by orubel** [comment]
Actually, I am working on a 4.0 build :)

If you want a 4.0 build, let me know and I can speed one up for you :)

Public demand always helps me know what people want.

Owen Rubel
orubel@gmail.com

**Comment by orubel** [comment]
closing as I haven't heard a response. Please reopen if you need additional help.
