### ISSUE TITLE
Could not find artifact org.grails.profiles:beapi:jar:1.4.10 in grailsCentral

### ISSUE THREAD

**Issue by hanyou** [orubel/Beapi-API-Framework#121]
**Describe the bug**
| Error Error occurred running Grails CLI: Could not find artifact org.grails.profiles:beapi:jar:1.4.10 in grailsCentral (https://repo.grails.org/grails/core) (Use --stacktrace to see the full trace)

**To Reproduce**
grails create-app testapi --profile org.grails.profiles:beapi:1.4.10

**Expected behavior**

**Environment: [e.g. iOS]
 - MacOS
 - 1.8.0_161-b12

**Comment by orubel** [comment]
I just built a repo this way yesterday and had no problem.  This isn't pulling from grailsCentral.  Should be pulling from bintray. Did you remove the bintray repos??

        // bintray
        maven { url "http://dl.bintray.com/orubel/plugins" }
        jcenter {
            url "http://jcenter.bintray.com/"
        }

**Comment by orubel** [comment]
I'm going to keep this open until I hear back. Let me know if you are still having this problem after checking if you still have those repos?

**Comment by orubel** [comment]
Going to kill this as I haven't heard back; assume it was just a configuration issue. Reopen if you have the same issue.
