### ISSUE TITLE
BeAPI Linux on Windows 10 Development - Error occurred running Grails CLI: Could not find artifact org.grails.profiles:beapi:jar:2.0.7 in grailsCentral (https://repo.grails.org/grails/core)

### ISSUE THREAD

**Issue by jimveloper** [orubel/Beapi-API-Framework#137]
1.	Introduction
This document provides a brief overview of topics discussed developing with BeAPI Framework on Windows 10.

2.	Windows Development Requirements

•	Build on Linux/Unix.
•	99.99% of web servers in production are *NIX based to the point that Microsoft now supports Linux on a mock shell.
•	Even Microsoft runs their web servers on Linux
•	BeAPI Framework always assume a Linux file system, not a Windows file system.
•	You should be building on the platform you are releasing for; hence, you should not be building on a Windows system if you are releasing on Linux.

However, many Developers have Windows as their Desktop environment.  This document attempts to outline a Windows development environment for the BeAPI framework.  There are two approaches; Windows Subsystem for Linux and VMWare Workstation. 

2.1	Windows Subsystem for Linux

2.1.1	Installing Linux Subsystem on Windows 10
https://itsfoss.com/install-bash-on-windows/

2.1.2	Install Java
https://java.com/en/download/help/linux_x64_install.xml

jajohga@jajohga-PC:/usr/java/jre1.8.0_261$ ls -l
total 8
-r--r--r-- 1 10143 10143 3244 Jun 18 02:55 COPYRIGHT
-r--r--r-- 1 10143 10143   44 Jun 18 02:55 LICENSE
-r--r--r-- 1 10143 10143   46 Jun 18 02:55 README
-rw-r--r-- 1 10143 10143  190 Jun 18 00:03 THIRDPARTYLICENSEREADME-JAVAFX.txt
-r--r--r-- 1 10143 10143  190 Jun 18 02:55 THIRDPARTYLICENSEREADME.txt
-r--r--r-- 1 10143 10143  955 Jun 18 02:55 Welcome.html
drwxr-xr-x 1 10143 10143 4096 Jun 18 02:55 bin
drwxr-xr-x 1 10143 10143 4096 Jun 18 02:55 legal
drwxr-xr-x 1 10143 10143 4096 Jun 18 03:00 lib
drwxr-xr-x 1 10143 10143 4096 Jun 18 02:55 man
drwxr-xr-x 1 10143 10143 4096 Jun 18 02:55 plugin
-rw-r--r-- 1 10143 10143  424 Jun 18 02:55 release

**This is the JRE, not JDK.  Is this an issue?**

2.1.3	Install Grails
Grails seems to have an OS-agnostic installation.

2.1.3.1	Linux/Unix OS Grails Installation Using Sdkman

Install sdkman

$ curl -s "https://get.sdkman.io" | bash

In order you want to continue working in the same terminal window execute

$ source "$HOME/.sdkman/bin/sdkman-init.sh"

To install the latest version of Grails simply run

$ sdk install grails 

or if need a specific version you can run

$ sdk install grails 2.4.3

2.1.3.2	Install Grails from Zip file
I used this method to install Grails.

•	Download grails-{desired version} zip file
•	Extract it into any folder.
•	Edit .bashrc in home folder such that

    JAVA_HOME=/path/to/java/jdk1.6.0_25-64/

    export JAVA_HOME PATH=$JAVA_HOME/bin:$PATH export PATH

    export GRAILS_HOME=/path/to/grails/grails-2.4.2/

    export PATH="$PATH:$GRAILS_HOME/bin"

•	Try to run grails command in terminal

jajohga@jajohga-PC:~$ grails -version
| Grails Version: 3.3.11
| JVM Version: 1.8.0_261

2.1.4	Special Notes

You can access the Windows C Drive:

cd /mnt/c

https://www.howtogeek.com/426749/how-to-access-your-linux-wsl-files-in-windows-10/
From within the Windows Subsystem for Linux environment you want to browse, run the following command:

explorer.exe .

This will launch File Explorer showing the current Linux directory—you can browse the Linux environment’s file system from there.

You can also access them directly at a \\wsl$ path. In File Explorer or any other Windows application that can browse files, navigate to the following path:

\\wsl$

You’ll see the folders for all your installed Linux distributions, which are exposed as if they were network shares. 

2.1.5	Install BeAPI

http://orubel.github.io/Beapi-API-Framework/

jajohga@jajohga-PC:/mnt/c/projects/PayTab/code/Server$ grails create-app PayTab --profile org.grails.profiles:beapi:2.0.7
Resolving dependencies..
| **Error Error occurred running Grails CLI: Could not find artifact org.grails.profiles:beapi:jar:2.0.7 in grailsCentral (https://repo.grails.org/grails/core)** (Use --stacktrace to see the full trace)

**However, rest-api works.**

jajohga@jajohga-PC:/mnt/c/projects/PayTab/code/Server$ grails create-app --profile rest-api
| Error Specify an application name or use --inplace to create an application in the current directory
jajohga@jajohga-PC:/mnt/c/projects/PayTab/code/Server$ grails create-app rest-api
| Application created at /mnt/c/projects/PayTab/code/Server/rest-api
jajohga@jajohga-PC:/mnt/c/projects/PayTab/code/Server$ cd rest-api
jajohga@jajohga-PC:/mnt/c/projects/PayTab/code/Server/rest-api$ ls -l
total 36
-rwxrwxrwx 1 jajohga jajohga 2952 Aug 16 14:01 build.gradle
drwxrwxrwx 1 jajohga jajohga 4096 Aug 16 14:01 gradle
-rwxrwxrwx 1 jajohga jajohga   73 Aug 16 14:01 gradle.properties
-rwxrwxrwx 1 jajohga jajohga 4971 Aug 16 14:01 gradlew
-rwxrwxrwx 1 jajohga jajohga 2404 Aug 16 14:01 gradlew.bat
drwxrwxrwx 1 jajohga jajohga 4096 Aug 16 14:01 grails-app
-rwxrwxrwx 1 jajohga jajohga 5463 Aug 16 14:01 grails-wrapper.jar
-rwxrwxrwx 1 jajohga jajohga 4672 Aug 16 14:01 grailsw
-rwxrwxrwx 1 jajohga jajohga 2375 Aug 16 14:01 grailsw.bat
drwxrwxrwx 1 jajohga jajohga 4096 Aug 16 14:01 src

2.2	VMWare Workstation

2.2.1	VMWare Workstation
Install VMWare Workstation 15

2.2.2	Ubuntu

ubuntu-20.04.1-desktop-amd64.iso

2.2.3	Install Java
https://java.com/en/download/help/linux_x64_install.xml

jajohga@ubuntu:/usr/java/jre1.8.0_261$ ls -l
total 48
drwxr-xr-x  2 10143 10143 4096 Jun 17 23:55 bin
-r--r--r--  1 10143 10143 3244 Jun 17 23:55 COPYRIGHT
drwxr-xr-x  4 10143 10143 4096 Jun 17 23:55 legal
drwxr-xr-x 15 10143 10143 4096 Jun 18 00:00 lib
-r--r--r--  1 10143 10143   44 Jun 17 23:55 LICENSE
drwxr-xr-x  4 10143 10143 4096 Jun 17 23:55 man
drwxr-xr-x  3 10143 10143 4096 Jun 17 23:55 plugin
-r--r--r--  1 10143 10143   46 Jun 17 23:55 README
-rw-r--r--  1 10143 10143  424 Jun 17 23:55 release
-rw-r--r--  1 10143 10143  190 Jun 17 21:03 THIRDPARTYLICENSEREADME-JAVAFX.txt
-r--r--r--  1 10143 10143  190 Jun 17 23:55 THIRDPARTYLICENSEREADME.txt
-r--r--r--  1 10143 10143  955 Jun 17 23:55 Welcome.html

**This is the JRE, not JDK.  Is this an issue?**

2.2.4	Install Grails
Grails seems to have an OS-agnostic installation.

•	Download grails-{desired version} zip file
•	Extract it into any folder.
•	Edit .bashrc in home folder such that

    JAVA_HOME=/path/to/java/jdk1.6.0_25-64/

    export JAVA_HOME PATH=$JAVA_HOME/bin:$PATH export PATH

    export GRAILS_HOME=/path/to/grails/grails-2.4.2/

    export PATH="$PATH:$GRAILS_HOME/bin"

•	Try to run grails command in terminal

jajohga@ubuntu:~$ grails -version
| Grails Version: 3.3.11
| JVM Version: 1.8.0_261

2.2.5	Install BeAPI

http://orubel.github.io/Beapi-API-Framework/

jajohga@ubuntu:~/projects/PayTab$ grails create-app PayTab --profile org.grails.profiles:beapi:2.0.7
| **Error Error occurred running Grails CLI: Could not find artifact org.grails.profiles:beapi:jar:2.0.7 in grailsCentral (https://repo.grails.org/grails/core)** (Use --stacktrace to see the full trace)

**However, rest-api works.**

jajohga@ubuntu:~/projects/PayTab$ grails create-app rest-api
| Application created at /home/jajohga/projects/PayTab/rest-api
jajohga@ubuntu:~/projects/PayTab$ cd rest-api
jajohga@ubuntu:~/projects/PayTab/rest-api$ ls -l
total 52
-rw-rw-r--  1 jajohga jajohga 2952 Aug 16 11:07 build.gradle
drwxrwxr-x  3 jajohga jajohga 4096 Aug 16 11:07 gradle
-rw-rw-r--  1 jajohga jajohga   73 Aug 16 11:07 gradle.properties
-rwxrw-r--  1 jajohga jajohga 4971 Aug 16 11:07 gradlew
-rwxrw-r--  1 jajohga jajohga 2404 Aug 16 11:07 gradlew.bat
drwxrwxr-x 12 jajohga jajohga 4096 Aug 16 11:07 grails-app
-rwxrw-r--  1 jajohga jajohga 4672 Aug 16 11:07 grailsw
-rwxrw-r--  1 jajohga jajohga 2375 Aug 16 11:07 grailsw.bat
-rw-rw-r--  1 jajohga jajohga 5463 Aug 16 11:07 grails-wrapper.jar
drwxrwxr-x  5 jajohga jajohga 4096 Aug 16 11:07 src

**Comment by orubel** [comment]
as stated in the documentation, the project requires Grails 3.3.x

you are installing grails 2

Please use appropriate version.

Closing issue.

**Comment by jimveloper** [comment]
Those were general instructions.  I can revise and resubmit.
grails -version
| Grails Version: 3.3.11
| JVM Version: 1.8.0_261

**Comment by orubel** [comment]
you previously stated that you installed grails2 with sdkman.

To proceed I'll need you to provide sdkman list of all installed versions as well as default version

**Comment by orubel** [comment]
this comment belongs in issue #139
